### ISSUE TITLE
Android Implementation 

### ISSUE THREAD

**Issue by Fshamri** [axierjhtjz/android-json-rpc#2]
vane you please guide me on how to use your library in my android app  with authentication (username and password)?

 thanks a lot

**Comment by axierjhtjz** [comment]
This is just a example of a login using the library. In this case callJSONObject will post data to a controller called "login".

```java
// Create client specifying JSON-RPC version 2.0
JSONRPCClient client = JSONRPCClient.create("http://service/uri", JSONRPCParams.Versions.VERSION_2);
client.setConnectionTimeout(2000);
client.setSoTimeout(2000);
try {
  JSONObject jsonObj = new JSONObject();
  jsonObj.put("user", "myuser");
  jsonObj.put("password", "mypassword");
  String string = client.callJSONObject("login", jsonObj);
} catch (JSONRPCException e) {
  e.printStackTrace();
}
```

**Comment by Fshamri** [comment]
Hi,
in fact i am trying to write android client by calling endpoint: https://github.com/miniflux/miniflux/blob/master/jsonrpc.php

as per your suggestion,  i have created the following method in my android app
 private String testMethod() {
        JSONRPCClient client = JSONRPCClient
                .create("http://localhost/minifluxR/jsonrpc.php",JSONRPCParams.Versions.VERSION_2);
        client.setConnectionTimeout(2000);
        client.setSoTimeout(2000);
        try {
            JSONObject jsonObj = new JSONObject();
            jsonObj.put("username", "admin");
            jsonObj.put("password", "e4d4face52f2e3dc22b43b2145ed7c58ce66e26b384d73592c");
            String string = client.callJSONObject("login", jsonObj);
        } catch (JSONRPCException e) {
            e.printStackTrace();
        }
        return string;
    }

but i am getting error for line  String string = client.callJSONObject("login", jsonObj) like the following:
 Error:(45, 50) error: incompatible types
required: String
found:    JSONObject

Can you please help me to write correct call to serve my purpose?

Thanks a lot for your guidance

**Comment by axierjhtjz** [comment]
My fault, the ```java client.callJSONObject("method", jsonObj); ``` returns a JSONObject not a string. 
Change ```java String string = client.callJSONObject("login", jsonObj);``` to ```java JSONObject responseObj = client.callJSONObject("login", jsonObj);```

**Comment by Fshamri** [comment]
Hi,
appreciate your response...
I just added the following to my onCreat method:
   @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        JSONRPCClient client = JSONRPCClient.create("http://www.amazfood.net/rss/jsonrpc.php", JSONRPCParams.Versions.VERSION_2);
        client.setConnectionTimeout(2000);
        client.setSoTimeout(2000);
        try {
            JSONObject jsonObj = new JSONObject();
            jsonObj.put("user", "admin");
            jsonObj.put("password", "e4d4face52f2e3dc22b43b2145ed7c58ce66e26b384d73592c");
            JSONObject responseObj = client.callJSONObject("feed.list", jsonObj);
        } catch (JSONRPCException e) {
            e.printStackTrace();
        } catch (JSONException e) {
            e.printStackTrace();
        }

But I am getting NetworkOnMainThreadException as follows: 

02-21 02:55:42.928  30469-30469/faiz.com.jsonrpc E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{faiz.com.jsonrpc/faiz.com.jsonrpc.MainActivity}: android.os.NetworkOnMainThreadException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2359)
            at android.app.ActivityThread.access$700(ActivityThread.java:165)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5455)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1144)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
            at java.net.InetAddress.getAllByName(InetAddress.java:214)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
            at org.alexd.jsonrpc.JSONRPCHttpClient.doJSONRequest(JSONRPCHttpClient.java:100)
            at org.alexd.jsonrpc.JSONRPCClient.doRequest(JSONRPCClient.java:108)
            at org.alexd.jsonrpc.JSONRPCClient.callJSONObject(JSONRPCClient.java:487)
            at faiz.com.jsonrpc.MainActivity.onCreate(MainActivity.java:28)
            at android.app.Activity.performCreate(Activity.java:5372)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2359)
            at android.app.ActivityThread.access$700(ActivityThread.java:165)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5455)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by axierjhtjz** [comment]
Android won't let you do any kind of networking on the main UI thread, try doing the call inside a Thread or an AsyncTask.
